# Generated by Django 2.2.7 on 2019-11-19 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc10', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
